name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21.0"
    - name: Run tests
      run: go test -mod=mod ./...
    - name: Trigger docker build
      run: curl -X POST $URL
      env:
        URL: ${{ secrets.DOCKERHUB_WEBHOOK }}
